name: error_handler_bloc
description: Error handling and management BLoC for the Flutter app template
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter
  
  equatable: ^2.0.5
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  app_logging:
    path: ../../app_lib/logging
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true